INSERT INTO TAX (MIN_VALUE, MAX_VALUE, MONEY_TAX, PERCENTAGE_TAX) VALUES (0, 0, 3.00, 1.25);
INSERT INTO TAX (MIN_VALUE, MAX_VALUE, MONEY_TAX, PERCENTAGE_TAX) VALUES (1, 10, 1.20, 0.0);
INSERT INTO TAX (MIN_VALUE, MAX_VALUE, MONEY_TAX, PERCENTAGE_TAX) VALUES (11, 20, 0.0, 8.2);
INSERT INTO TAX (MIN_VALUE, MAX_VALUE, MONEY_TAX, PERCENTAGE_TAX) VALUES (21, 30, 0.0, 6.9);
INSERT INTO TAX (MIN_VALUE, MAX_VALUE, MONEY_TAX, PERCENTAGE_TAX) VALUES (31, 40, 0.0, 4.7);
INSERT INTO TAX (MIN_VALUE, MAX_VALUE, MONEY_TAX, PERCENTAGE_TAX) VALUES (41, 50, 0.0, 1.7);
